# Site settings
title: "Mo Khan"
description: "Staff Software Engineer, VMware"
url: "https://monis.app"

# User settings
username: "Mo Khan"
user_title: "Staff Software Engineer, VMware"
email: "i@monis.app"
github_username: "enj"
stack_overflow_cv: "m"

exclude: ['package.json', 'src' , 'node_modules']
